# Generated by Django 5.2 on 2025-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0004_remove_project_category_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='students',
            new_name='members',
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
