# Generated by Django 5.2 on 2025-04-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0006_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
